// Mock Data Generation Date: 2026-02-06T08:26:56.606Z
export const MOCK_PRODUCTS = [
  {
    "Product_Category": "Bookshelf",
    "Owner": {
      "name": "Ankita Singh",
      "id": "4301492000000425001",
      "email": "ankita.singh@bluewud.com"
    },
    "Ususal_Price": null,
    "$currency_symbol": "₹",
    "$field_states": null,
    "$review_process": {
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Channel_Price": null,
    "Product_MTP_Name": "Barnia Bookshelf",
    "$layout_id": {
      "display_label": "Standard",
      "name": "Standard",
      "id": "4301492000076159290"
    },
    "Name": "SB-BNA",
    "Last_Activity_Time": "2026-02-05T19:22:37+05:30",
    "Installation_Price": null,
    "$review": null,
    "$state": "save",
    "Unsubscribed_Mode": null,
    "$process_flow": false,
    "Exchange_Rate": 1,
    "Billed_Volumetric_Weight": null,
    "Currency": "INR",
    "Billed_Chargeable_Weight": null,
    "$locked_for_me": false,
    "id": "4301492000081836052",
    "ProductActive": "Active Product",
    "Total_Weight": 16.87,
    "$approved": true,
    "$approval": {
      "delegate": false,
      "takeover": false,
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Installation": null,
    "Unsubscribed_Time": null,
    "$editable": true,
    "Processing_Status": null,
    "$orchestration": false,
    "Weight_Category_Billed": "20kg",
    "Billed_Physical_Weight": null,
    "$in_merge": false,
    "Locked__s": false,
    "Audit_History_Log": null,
    "BOM_Weight": null,
    "Tag": [],
    "$zia_owner_assignment": "owner_recommendation_unavailable",
    "$approval_state": "approved",
    "Unit_Price": 6199,
    "soldsPerMonth": 45,
    "shippingCostPerKg": 25,
    "Live_Status": "Y"
  },
  {
    "Product_Category": "Wardrobe",
    "Owner": {
      "name": "Ankita Singh",
      "id": "4301492000000425001",
      "email": "ankita.singh@bluewud.com"
    },
    "Ususal_Price": null,
    "$currency_symbol": "₹",
    "$field_states": null,
    "$review_process": {
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Channel_Price": null,
    "Product_MTP_Name": "Calcio Combo Wardrobe",
    "$layout_id": {
      "display_label": "Standard",
      "name": "Standard",
      "id": "4301492000076159290"
    },
    "Name": "W-CLO-345",
    "Last_Activity_Time": "2026-02-05T19:22:03+05:30",
    "Installation_Price": null,
    "$review": null,
    "$state": "save",
    "Unsubscribed_Mode": null,
    "$process_flow": false,
    "Exchange_Rate": 1,
    "Billed_Volumetric_Weight": null,
    "Currency": "INR",
    "Billed_Chargeable_Weight": null,
    "$locked_for_me": false,
    "id": "4301492000081836034",
    "ProductActive": "Active Product",
    "Total_Weight": 73.6,
    "$approved": true,
    "$approval": {
      "delegate": false,
      "takeover": false,
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Installation": null,
    "Unsubscribed_Time": null,
    "$editable": true,
    "Processing_Status": null,
    "$orchestration": false,
    "Weight_Category_Billed": "100kg",
    "Billed_Physical_Weight": null,
    "$in_merge": false,
    "Locked__s": false,
    "Audit_History_Log": null,
    "BOM_Weight": null,
    "Tag": [],
    "$zia_owner_assignment": "owner_recommendation_unavailable",
    "$approval_state": "approved",
    "Unit_Price": 23999,
    "soldsPerMonth": 12,
    "shippingCostPerKg": 32,
    "Live_Status": "Y"
  },
  {
    "Product_Category": "Furniture",
    "Owner": {
      "name": "Ankita Singh",
      "id": "4301492000000425001",
      "email": "ankita.singh@bluewud.com"
    },
    "Ususal_Price": null,
    "$currency_symbol": "₹",
    "$field_states": null,
    "$review_process": {
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Channel_Price": null,
    "Product_MTP_Name": "Stuart 21 Key Holder",
    "$layout_id": {
      "display_label": "Standard",
      "name": "Standard",
      "id": "4301492000076159290"
    },
    "Name": "KH-SUT-21",
    "Last_Activity_Time": "2026-02-05T19:20:43+05:30",
    "Installation_Price": null,
    "$review": null,
    "$state": "save",
    "Unsubscribed_Mode": null,
    "$process_flow": false,
    "Exchange_Rate": 1,
    "Billed_Volumetric_Weight": null,
    "Currency": "INR",
    "Billed_Chargeable_Weight": null,
    "$locked_for_me": false,
    "id": "4301492000081836016",
    "ProductActive": "Active Product",
    "Total_Weight": 0.75,
    "$approved": true,
    "$approval": {
      "delegate": false,
      "takeover": false,
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Installation": null,
    "Unsubscribed_Time": null,
    "$editable": true,
    "Processing_Status": null,
    "$orchestration": false,
    "Weight_Category_Billed": "5kg",
    "Billed_Physical_Weight": null,
    "$in_merge": false,
    "Locked__s": false,
    "Audit_History_Log": null,
    "BOM_Weight": null,
    "Tag": [],
    "$zia_owner_assignment": "owner_recommendation_unavailable",
    "$approval_state": "approved",
    "Unit_Price": 1999,
    "soldsPerMonth": 85,
    "shippingCostPerKg": 22,
    "Live_Status": "Y"
  },
  {
    "Product_Category": "Bookshelf",
    "Owner": {
      "name": "Ankita Singh",
      "id": "4301492000000425001",
      "email": "ankita.singh@bluewud.com"
    },
    "Ususal_Price": null,
    "$currency_symbol": "₹",
    "$field_states": null,
    "$review_process": {
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Channel_Price": null,
    "Product_MTP_Name": "Novebuk Bookshelf",
    "$layout_id": {
      "display_label": "Standard",
      "name": "Standard",
      "id": "4301492000076159290"
    },
    "Name": "SB-NBK",
    "Last_Activity_Time": "2026-02-05T19:19:51+05:30",
    "Installation_Price": null,
    "$review": null,
    "$state": "save",
    "Unsubscribed_Mode": null,
    "$process_flow": false,
    "Exchange_Rate": 1,
    "Billed_Volumetric_Weight": null,
    "Currency": "INR",
    "Billed_Chargeable_Weight": null,
    "$locked_for_me": false,
    "id": "4301492000081836008",
    "ProductActive": "Active Product",
    "Total_Weight": 18.8,
    "$approved": true,
    "$approval": {
      "delegate": false,
      "takeover": false,
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Installation": null,
    "Unsubscribed_Time": null,
    "$editable": true,
    "Processing_Status": null,
    "$orchestration": false,
    "Weight_Category_Billed": "20kg",
    "Billed_Physical_Weight": null,
    "$in_merge": false,
    "Locked__s": false,
    "Audit_History_Log": null,
    "BOM_Weight": null,
    "Tag": [],
    "$zia_owner_assignment": "owner_recommendation_unavailable",
    "$approval_state": "approved",
    "Unit_Price": 7799
  },
  {
    "Product_Category": "Wardrobe",
    "Owner": {
      "name": "Ankita Singh",
      "id": "4301492000000425001",
      "email": "ankita.singh@bluewud.com"
    },
    "Ususal_Price": null,
    "$currency_symbol": "₹",
    "$field_states": null,
    "$review_process": {
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Channel_Price": null,
    "Product_MTP_Name": "Calcio 5-Tier Wardrobe",
    "$layout_id": {
      "display_label": "Standard",
      "name": "Standard",
      "id": "4301492000076159290"
    },
    "Name": "W-CLO-5",
    "Last_Activity_Time": "2026-02-05T19:22:13+05:30",
    "Installation_Price": null,
    "$review": null,
    "$state": "save",
    "Unsubscribed_Mode": null,
    "$process_flow": false,
    "Exchange_Rate": 1,
    "Billed_Volumetric_Weight": null,
    "Currency": "INR",
    "Billed_Chargeable_Weight": null,
    "$locked_for_me": false,
    "id": "4301492000081834088",
    "ProductActive": "Active Product",
    "Total_Weight": 29.5,
    "$approved": true,
    "$approval": {
      "delegate": false,
      "takeover": false,
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Installation": null,
    "Unsubscribed_Time": null,
    "$editable": true,
    "Processing_Status": null,
    "$orchestration": false,
    "Weight_Category_Billed": "50kg",
    "Billed_Physical_Weight": null,
    "$in_merge": false,
    "Locked__s": false,
    "Audit_History_Log": null,
    "BOM_Weight": null,
    "Tag": [],
    "$zia_owner_assignment": "owner_recommendation_unavailable",
    "$approval_state": "approved",
    "Unit_Price": 10499
  },
  {
    "Product_Category": "Furniture",
    "Owner": {
      "name": "Ankita Singh",
      "id": "4301492000000425001",
      "email": "ankita.singh@bluewud.com"
    },
    "Ususal_Price": null,
    "$currency_symbol": "₹",
    "$field_states": null,
    "$review_process": {
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Channel_Price": null,
    "Product_MTP_Name": "Norel Monitor Stand",
    "$layout_id": {
      "display_label": "Standard",
      "name": "Standard",
      "id": "4301492000076159290"
    },
    "Name": "TS-NL",
    "Last_Activity_Time": "2026-02-05T19:19:41+05:30",
    "Installation_Price": null,
    "$review": null,
    "$state": "save",
    "Unsubscribed_Mode": null,
    "$process_flow": false,
    "Exchange_Rate": 1,
    "Billed_Volumetric_Weight": null,
    "Currency": "INR",
    "Billed_Chargeable_Weight": null,
    "$locked_for_me": false,
    "id": "4301492000081834063",
    "ProductActive": "Active Product",
    "Total_Weight": null,
    "$approved": true,
    "$approval": {
      "delegate": false,
      "takeover": false,
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Installation": null,
    "Unsubscribed_Time": null,
    "$editable": true,
    "Processing_Status": null,
    "$orchestration": false,
    "Weight_Category_Billed": "Unknown",
    "Billed_Physical_Weight": null,
    "$in_merge": false,
    "Locked__s": false,
    "Audit_History_Log": null,
    "BOM_Weight": null,
    "Tag": [],
    "$zia_owner_assignment": "owner_recommendation_unavailable",
    "$approval_state": "approved",
    "Unit_Price": 899
  },
  {
    "Product_Category": "Table",
    "Owner": {
      "name": "Ankita Singh",
      "id": "4301492000000425001",
      "email": "ankita.singh@bluewud.com"
    },
    "Ususal_Price": null,
    "$currency_symbol": "₹",
    "$field_states": null,
    "$review_process": {
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Channel_Price": null,
    "Product_MTP_Name": "Victor Coffee Table",
    "$layout_id": {
      "display_label": "Standard",
      "name": "Standard",
      "id": "4301492000076159290"
    },
    "Name": "CT-VC",
    "Last_Activity_Time": "2026-02-05T19:18:44+05:30",
    "Installation_Price": null,
    "$review": null,
    "$state": "save",
    "Unsubscribed_Mode": null,
    "$process_flow": false,
    "Exchange_Rate": 1,
    "Billed_Volumetric_Weight": null,
    "Currency": "INR",
    "Billed_Chargeable_Weight": null,
    "$locked_for_me": false,
    "id": "4301492000081834043",
    "ProductActive": "Active Product",
    "Total_Weight": 14.8,
    "$approved": true,
    "$approval": {
      "delegate": false,
      "takeover": false,
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Installation": null,
    "Unsubscribed_Time": null,
    "$editable": true,
    "Processing_Status": null,
    "$orchestration": false,
    "Weight_Category_Billed": "20kg",
    "Billed_Physical_Weight": null,
    "$in_merge": false,
    "Locked__s": false,
    "Audit_History_Log": null,
    "BOM_Weight": null,
    "Tag": [],
    "$zia_owner_assignment": "owner_recommendation_unavailable",
    "$approval_state": "approved",
    "Unit_Price": 6999
  },
  {
    "Product_Category": "TV Unit",
    "Owner": {
      "name": "Ankita Singh",
      "id": "4301492000000425001",
      "email": "ankita.singh@bluewud.com"
    },
    "Ususal_Price": null,
    "$currency_symbol": "₹",
    "$field_states": null,
    "$review_process": {
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Channel_Price": null,
    "Product_MTP_Name": "Maisy Standard TV Unit",
    "$layout_id": {
      "display_label": "Standard",
      "name": "Standard",
      "id": "4301492000076159290"
    },
    "Name": "TU-MA-ST",
    "Last_Activity_Time": "2026-02-05T19:18:19+05:30",
    "Installation_Price": null,
    "$review": null,
    "$state": "save",
    "Unsubscribed_Mode": null,
    "$process_flow": false,
    "Exchange_Rate": 1,
    "Billed_Volumetric_Weight": null,
    "Currency": "INR",
    "Billed_Chargeable_Weight": null,
    "$locked_for_me": false,
    "id": "4301492000081834035",
    "ProductActive": "Active Product",
    "Total_Weight": 2.85,
    "$approved": true,
    "$approval": {
      "delegate": false,
      "takeover": false,
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Installation": null,
    "Unsubscribed_Time": null,
    "$editable": true,
    "Processing_Status": null,
    "$orchestration": false,
    "Weight_Category_Billed": "5kg",
    "Billed_Physical_Weight": null,
    "$in_merge": false,
    "Locked__s": false,
    "Audit_History_Log": null,
    "BOM_Weight": null,
    "Tag": [],
    "$zia_owner_assignment": "owner_recommendation_unavailable",
    "$approval_state": "approved",
    "Unit_Price": 1999,
    "soldsPerMonth": 85,
    "shippingCostPerKg": 22,
    "Live_Status": "Y"
  },
  {
    "Product_Category": "Furniture",
    "Owner": {
      "name": "Ankita Singh",
      "id": "4301492000000425001",
      "email": "ankita.singh@bluewud.com"
    },
    "Ususal_Price": null,
    "$currency_symbol": "₹",
    "$field_states": null,
    "$review_process": {
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Channel_Price": null,
    "Product_MTP_Name": "Roland Remote Holder",
    "$layout_id": {
      "display_label": "Standard",
      "name": "Standard",
      "id": "4301492000076159290"
    },
    "Name": "RH-RL",
    "Last_Activity_Time": "2026-02-05T19:17:55+05:30",
    "Installation_Price": null,
    "$review": null,
    "$state": "save",
    "Unsubscribed_Mode": null,
    "$process_flow": false,
    "Exchange_Rate": 1,
    "Billed_Volumetric_Weight": null,
    "Currency": "INR",
    "Billed_Chargeable_Weight": null,
    "$locked_for_me": false,
    "id": "4301492000081834017",
    "ProductActive": "Active Product",
    "Total_Weight": 0.7,
    "$approved": true,
    "$approval": {
      "delegate": false,
      "takeover": false,
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Installation": null,
    "Unsubscribed_Time": null,
    "$editable": true,
    "Processing_Status": null,
    "$orchestration": false,
    "Weight_Category_Billed": "5kg",
    "Billed_Physical_Weight": null,
    "$in_merge": false,
    "Locked__s": false,
    "Audit_History_Log": null,
    "BOM_Weight": null,
    "Tag": [],
    "$zia_owner_assignment": "owner_recommendation_unavailable",
    "$approval_state": "approved",
    "Unit_Price": 1199
  },
  {
    "Product_Category": "Table",
    "Owner": {
      "name": "Ankita Singh",
      "id": "4301492000000425001",
      "email": "ankita.singh@bluewud.com"
    },
    "Ususal_Price": null,
    "$currency_symbol": "₹",
    "$field_states": null,
    "$review_process": {
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Channel_Price": null,
    "Product_MTP_Name": "Ender End Table",
    "$layout_id": {
      "display_label": "Standard",
      "name": "Standard",
      "id": "4301492000076159290"
    },
    "Name": "FT-EDR",
    "Last_Activity_Time": "2026-02-05T19:17:35+05:30",
    "Installation_Price": null,
    "$review": null,
    "$state": "save",
    "Unsubscribed_Mode": null,
    "$process_flow": false,
    "Exchange_Rate": 1,
    "Billed_Volumetric_Weight": null,
    "Currency": "INR",
    "Billed_Chargeable_Weight": null,
    "$locked_for_me": false,
    "id": "4301492000081834003",
    "ProductActive": "Active Product",
    "Total_Weight": 8.85,
    "$approved": true,
    "$approval": {
      "delegate": false,
      "takeover": false,
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Installation": null,
    "Unsubscribed_Time": null,
    "$editable": true,
    "Processing_Status": null,
    "$orchestration": false,
    "Weight_Category_Billed": "10kg",
    "Billed_Physical_Weight": null,
    "$in_merge": false,
    "Locked__s": false,
    "Audit_History_Log": null,
    "BOM_Weight": null,
    "Tag": [],
    "$zia_owner_assignment": "owner_recommendation_unavailable",
    "$approval_state": "approved",
    "Unit_Price": 3599
  },
  {
    "Product_Category": "Furniture",
    "Owner": {
      "name": "Ankita Singh",
      "id": "4301492000000425001",
      "email": "ankita.singh@bluewud.com"
    },
    "Ususal_Price": null,
    "$currency_symbol": "₹",
    "$field_states": null,
    "$review_process": {
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Channel_Price": null,
    "Product_MTP_Name": "SB-SDA",
    "$layout_id": {
      "display_label": "Standard",
      "name": "Standard",
      "id": "4301492000076159290"
    },
    "Name": "SB-SDA",
    "Last_Activity_Time": "2026-02-05T19:24:51+05:30",
    "Installation_Price": null,
    "$review": null,
    "$state": "save",
    "Unsubscribed_Mode": null,
    "$process_flow": false,
    "Exchange_Rate": 1,
    "Billed_Volumetric_Weight": null,
    "Currency": "INR",
    "Billed_Chargeable_Weight": null,
    "$locked_for_me": false,
    "id": "4301492000081833060",
    "ProductActive": "Discontinued Product",
    "Total_Weight": null,
    "$approved": true,
    "$approval": {
      "delegate": false,
      "takeover": false,
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Installation": null,
    "Unsubscribed_Time": null,
    "$editable": true,
    "Processing_Status": null,
    "$orchestration": false,
    "Weight_Category_Billed": null,
    "Billed_Physical_Weight": null,
    "$in_merge": false,
    "Locked__s": false,
    "Audit_History_Log": null,
    "BOM_Weight": null,
    "Tag": [],
    "$zia_owner_assignment": "owner_recommendation_unavailable",
    "$approval_state": "approved",
    "Unit_Price": 0
  },
  {
    "Product_Category": "Furniture",
    "Owner": {
      "name": "Ankita Singh",
      "id": "4301492000000425001",
      "email": "ankita.singh@bluewud.com"
    },
    "Ususal_Price": null,
    "$currency_symbol": "₹",
    "$field_states": null,
    "$review_process": {
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Channel_Price": null,
    "Product_MTP_Name": "Shubh Mini Pooja Temple",
    "$layout_id": {
      "display_label": "Standard",
      "name": "Standard",
      "id": "4301492000076159290"
    },
    "Name": "PU-SUB-ST",
    "Last_Activity_Time": "2026-02-05T19:23:19+05:30",
    "Installation_Price": null,
    "$review": null,
    "$state": "save",
    "Unsubscribed_Mode": null,
    "$process_flow": false,
    "Exchange_Rate": 1,
    "Billed_Volumetric_Weight": null,
    "Currency": "INR",
    "Billed_Chargeable_Weight": null,
    "$locked_for_me": false,
    "id": "4301492000081833045",
    "ProductActive": "Active Product",
    "Total_Weight": 12.8,
    "$approved": true,
    "$approval": {
      "delegate": false,
      "takeover": false,
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Installation": null,
    "Unsubscribed_Time": null,
    "$editable": true,
    "Processing_Status": null,
    "$orchestration": false,
    "Weight_Category_Billed": "20kg",
    "Billed_Physical_Weight": null,
    "$in_merge": false,
    "Locked__s": false,
    "Audit_History_Log": null,
    "BOM_Weight": null,
    "Tag": [],
    "$zia_owner_assignment": "owner_recommendation_unavailable",
    "$approval_state": "approved",
    "Unit_Price": 7999
  },
  {
    "Product_Category": "Furniture",
    "Owner": {
      "name": "Ankita Singh",
      "id": "4301492000000425001",
      "email": "ankita.singh@bluewud.com"
    },
    "Ususal_Price": null,
    "$currency_symbol": "₹",
    "$field_states": null,
    "$review_process": {
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Channel_Price": null,
    "Product_MTP_Name": "Promys Set of Two Wall Art",
    "$layout_id": {
      "display_label": "Standard",
      "name": "Standard",
      "id": "4301492000076159290"
    },
    "Name": "WA-PYS-N",
    "Last_Activity_Time": "2026-02-05T19:21:38+05:30",
    "Installation_Price": null,
    "$review": null,
    "$state": "save",
    "Unsubscribed_Mode": null,
    "$process_flow": false,
    "Exchange_Rate": 1,
    "Billed_Volumetric_Weight": null,
    "Currency": "INR",
    "Billed_Chargeable_Weight": null,
    "$locked_for_me": false,
    "id": "4301492000081833029",
    "ProductActive": "Active Product",
    "Total_Weight": 1.89,
    "$approved": true,
    "$approval": {
      "delegate": false,
      "takeover": false,
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Installation": null,
    "Unsubscribed_Time": null,
    "$editable": true,
    "Processing_Status": null,
    "$orchestration": false,
    "Weight_Category_Billed": "5kg",
    "Billed_Physical_Weight": null,
    "$in_merge": false,
    "Locked__s": false,
    "Audit_History_Log": null,
    "BOM_Weight": null,
    "Tag": [],
    "$zia_owner_assignment": "owner_recommendation_unavailable",
    "$approval_state": "approved",
    "Unit_Price": 2399
  },
  {
    "Product_Category": "Furniture",
    "Owner": {
      "name": "Ankita Singh",
      "id": "4301492000000425001",
      "email": "ankita.singh@bluewud.com"
    },
    "Ususal_Price": null,
    "$currency_symbol": "₹",
    "$field_states": null,
    "$review_process": {
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Channel_Price": null,
    "Product_MTP_Name": "Edell Key Holder",
    "$layout_id": {
      "display_label": "Standard",
      "name": "Standard",
      "id": "4301492000076159290"
    },
    "Name": "KH-EDL",
    "Last_Activity_Time": "2026-02-05T19:20:37+05:30",
    "Installation_Price": null,
    "$review": null,
    "$state": "save",
    "Unsubscribed_Mode": null,
    "$process_flow": false,
    "Exchange_Rate": 1,
    "Billed_Volumetric_Weight": null,
    "Currency": "INR",
    "Billed_Chargeable_Weight": null,
    "$locked_for_me": false,
    "id": "4301492000081833021",
    "ProductActive": "Active Product",
    "Total_Weight": 0.34,
    "$approved": true,
    "$approval": {
      "delegate": false,
      "takeover": false,
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Installation": null,
    "Unsubscribed_Time": null,
    "$editable": true,
    "Processing_Status": null,
    "$orchestration": false,
    "Weight_Category_Billed": "5kg",
    "Billed_Physical_Weight": null,
    "$in_merge": false,
    "Locked__s": false,
    "Audit_History_Log": null,
    "BOM_Weight": null,
    "Tag": [],
    "$zia_owner_assignment": "owner_recommendation_unavailable",
    "$approval_state": "approved",
    "Unit_Price": 499
  },
  {
    "Product_Category": "Table",
    "Owner": {
      "name": "Ankita Singh",
      "id": "4301492000000425001",
      "email": "ankita.singh@bluewud.com"
    },
    "Ususal_Price": null,
    "$currency_symbol": "₹",
    "$field_states": null,
    "$review_process": {
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Channel_Price": null,
    "Product_MTP_Name": "Oliver Coffee Table",
    "$layout_id": {
      "display_label": "Standard",
      "name": "Standard",
      "id": "4301492000076159290"
    },
    "Name": "CT-OL",
    "Last_Activity_Time": "2026-02-05T19:20:20+05:30",
    "Installation_Price": null,
    "$review": null,
    "$state": "save",
    "Unsubscribed_Mode": null,
    "$process_flow": false,
    "Exchange_Rate": 1,
    "Billed_Volumetric_Weight": null,
    "Currency": "INR",
    "Billed_Chargeable_Weight": null,
    "$locked_for_me": false,
    "id": "4301492000081833013",
    "ProductActive": "Active Product",
    "Total_Weight": 10.87,
    "$approved": true,
    "$approval": {
      "delegate": false,
      "takeover": false,
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Installation": null,
    "Unsubscribed_Time": null,
    "$editable": true,
    "Processing_Status": null,
    "$orchestration": false,
    "Weight_Category_Billed": "20kg",
    "Billed_Physical_Weight": null,
    "$in_merge": false,
    "Locked__s": false,
    "Audit_History_Log": null,
    "BOM_Weight": null,
    "Tag": [],
    "$zia_owner_assignment": "owner_recommendation_unavailable",
    "$approval_state": "approved",
    "Unit_Price": 4899
  },
  {
    "Product_Category": "Sofa",
    "Owner": {
      "name": "Ankita Singh",
      "id": "4301492000000425001",
      "email": "ankita.singh@bluewud.com"
    },
    "Ususal_Price": null,
    "$currency_symbol": "₹",
    "$field_states": null,
    "$review_process": {
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Channel_Price": null,
    "Product_MTP_Name": "Wilber 3+1, 4 Seater Interchangeable L Shape Sofa",
    "$layout_id": {
      "display_label": "Standard",
      "name": "Standard",
      "id": "4301492000076159290"
    },
    "Name": "SF-WBR-4LI",
    "Last_Activity_Time": "2026-02-05T19:22:41+05:30",
    "Installation_Price": null,
    "$review": null,
    "$state": "save",
    "Unsubscribed_Mode": null,
    "$process_flow": false,
    "Exchange_Rate": 1,
    "Billed_Volumetric_Weight": null,
    "Currency": "INR",
    "Billed_Chargeable_Weight": null,
    "$locked_for_me": false,
    "id": "4301492000081832078",
    "ProductActive": "Active Product",
    "Total_Weight": 53.6,
    "$approved": true,
    "$approval": {
      "delegate": false,
      "takeover": false,
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Installation": null,
    "Unsubscribed_Time": null,
    "$editable": true,
    "Processing_Status": null,
    "$orchestration": false,
    "Weight_Category_Billed": "100kg",
    "Billed_Physical_Weight": null,
    "$in_merge": false,
    "Locked__s": false,
    "Audit_History_Log": null,
    "BOM_Weight": null,
    "Tag": [],
    "$zia_owner_assignment": "owner_recommendation_unavailable",
    "$approval_state": "approved",
    "Unit_Price": 25799
  },
  {
    "Product_Category": "Wardrobe",
    "Owner": {
      "name": "Ankita Singh",
      "id": "4301492000000425001",
      "email": "ankita.singh@bluewud.com"
    },
    "Ususal_Price": null,
    "$currency_symbol": "₹",
    "$field_states": null,
    "$review_process": {
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Channel_Price": null,
    "Product_MTP_Name": "Calcio 3-Tier Wardrobe",
    "$layout_id": {
      "display_label": "Standard",
      "name": "Standard",
      "id": "4301492000076159290"
    },
    "Name": "W-CLO-3",
    "Last_Activity_Time": "2026-02-05T19:22:06+05:30",
    "Installation_Price": null,
    "$review": null,
    "$state": "save",
    "Unsubscribed_Mode": null,
    "$process_flow": false,
    "Exchange_Rate": 1,
    "Billed_Volumetric_Weight": null,
    "Currency": "INR",
    "Billed_Chargeable_Weight": null,
    "$locked_for_me": false,
    "id": "4301492000081832070",
    "ProductActive": "Active Product",
    "Total_Weight": 17.7,
    "$approved": true,
    "$approval": {
      "delegate": false,
      "takeover": false,
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Installation": null,
    "Unsubscribed_Time": null,
    "$editable": true,
    "Processing_Status": null,
    "$orchestration": false,
    "Weight_Category_Billed": "20kg",
    "Billed_Physical_Weight": null,
    "$in_merge": false,
    "Locked__s": false,
    "Audit_History_Log": null,
    "BOM_Weight": null,
    "Tag": [],
    "$zia_owner_assignment": "owner_recommendation_unavailable",
    "$approval_state": "approved",
    "Unit_Price": 7299
  },
  {
    "Product_Category": "Bookshelf",
    "Owner": {
      "name": "Ankita Singh",
      "id": "4301492000000425001",
      "email": "ankita.singh@bluewud.com"
    },
    "Ususal_Price": null,
    "$currency_symbol": "₹",
    "$field_states": null,
    "$review_process": {
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Channel_Price": null,
    "Product_MTP_Name": "Aaron Bookshelf",
    "$layout_id": {
      "display_label": "Standard",
      "name": "Standard",
      "id": "4301492000076159290"
    },
    "Name": "SB-AA",
    "Last_Activity_Time": "2026-02-05T19:20:35+05:30",
    "Installation_Price": null,
    "$review": null,
    "$state": "save",
    "Unsubscribed_Mode": null,
    "$process_flow": false,
    "Exchange_Rate": 1,
    "Billed_Volumetric_Weight": null,
    "Currency": "INR",
    "Billed_Chargeable_Weight": null,
    "$locked_for_me": false,
    "id": "4301492000081832048",
    "ProductActive": "Active Product",
    "Total_Weight": 1.69,
    "$approved": true,
    "$approval": {
      "delegate": false,
      "takeover": false,
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Installation": null,
    "Unsubscribed_Time": null,
    "$editable": true,
    "Processing_Status": null,
    "$orchestration": false,
    "Weight_Category_Billed": "5kg",
    "Billed_Physical_Weight": null,
    "$in_merge": false,
    "Locked__s": false,
    "Audit_History_Log": null,
    "BOM_Weight": null,
    "Tag": [],
    "$zia_owner_assignment": "owner_recommendation_unavailable",
    "$approval_state": "approved",
    "Unit_Price": 1199
  },
  {
    "Product_Category": "Table",
    "Owner": {
      "name": "Ankita Singh",
      "id": "4301492000000425001",
      "email": "ankita.singh@bluewud.com"
    },
    "Ususal_Price": null,
    "$currency_symbol": "₹",
    "$field_states": null,
    "$review_process": {
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Channel_Price": null,
    "Product_MTP_Name": "Taury Rectangle Coffee Table",
    "$layout_id": {
      "display_label": "Standard",
      "name": "Standard",
      "id": "4301492000076159290"
    },
    "Name": "CT-TR-RT",
    "Last_Activity_Time": "2026-02-05T19:18:07+05:30",
    "Installation_Price": null,
    "$review": null,
    "$state": "save",
    "Unsubscribed_Mode": null,
    "$process_flow": false,
    "Exchange_Rate": 1,
    "Billed_Volumetric_Weight": null,
    "Currency": "INR",
    "Billed_Chargeable_Weight": null,
    "$locked_for_me": false,
    "id": "4301492000081832040",
    "ProductActive": "Active Product",
    "Total_Weight": 11.8,
    "$approved": true,
    "$approval": {
      "delegate": false,
      "takeover": false,
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Installation": null,
    "Unsubscribed_Time": null,
    "$editable": true,
    "Processing_Status": null,
    "$orchestration": false,
    "Weight_Category_Billed": "20kg",
    "Billed_Physical_Weight": null,
    "$in_merge": false,
    "Locked__s": false,
    "Audit_History_Log": null,
    "BOM_Weight": null,
    "Tag": [],
    "$zia_owner_assignment": "owner_recommendation_unavailable",
    "$approval_state": "approved",
    "Unit_Price": 6449
  },
  {
    "Product_Category": "TV Unit",
    "Owner": {
      "name": "Ankita Singh",
      "id": "4301492000000425001",
      "email": "ankita.singh@bluewud.com"
    },
    "Ususal_Price": null,
    "$currency_symbol": "₹",
    "$field_states": null,
    "$review_process": {
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Channel_Price": null,
    "Product_MTP_Name": "Toska Large TV Unit",
    "$layout_id": {
      "display_label": "Standard",
      "name": "Standard",
      "id": "4301492000076159290"
    },
    "Name": "TU-TK-LA",
    "Last_Activity_Time": "2026-02-05T19:16:59+05:30",
    "Installation_Price": null,
    "$review": null,
    "$state": "save",
    "Unsubscribed_Mode": null,
    "$process_flow": false,
    "Exchange_Rate": 1,
    "Billed_Volumetric_Weight": null,
    "Currency": "INR",
    "Billed_Chargeable_Weight": null,
    "$locked_for_me": false,
    "id": "4301492000081832026",
    "ProductActive": "Active Product",
    "Total_Weight": 7.8,
    "$approved": true,
    "$approval": {
      "delegate": false,
      "takeover": false,
      "approve": false,
      "reject": false,
      "resubmit": false
    },
    "Installation": null,
    "Unsubscribed_Time": null,
    "$editable": true,
    "Processing_Status": null,
    "$orchestration": false,
    "Weight_Category_Billed": "10kg",
    "Billed_Physical_Weight": null,
    "$in_merge": false,
    "Locked__s": false,
    "Audit_History_Log": null,
    "BOM_Weight": null,
    "Tag": [],
    "$zia_owner_assignment": "owner_recommendation_unavailable",
    "$approval_state": "approved",
    "Unit_Price": 3499
  }
];